steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.5.2':
        build: fusion-plugin-apollo-server
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':flowtype:'
    command: yarn flow
    plugins:
      'docker-compose#v1.5.2':
        run: fusion-plugin-apollo-server
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.5.2':
        run: fusion-plugin-apollo-server
    agents:
      queue: workers
  - name: ':chrome: :white_check_mark:'
    command: .buildkite/browserTests
    plugins:
      'docker-compose#v1.5.2':
        run: fusion-plugin-apollo-server
    agents:
      queue: workers
  - name: ':node: :white_check_mark:'
    command: .buildkite/nodeTests
    plugins:
      'docker-compose#v1.5.2':
        run: fusion-plugin-apollo-server
    agents:
      queue: workers
